### ISSUE TITLE
Undefined method alias_method_chain on embedded_in

### ISSUE THREAD

**Issue by canavese** [glooko/mongoid-embedded-errors#11]
I'm trying to upgrade Rails to 5.1.3 and am encountering this issue when a Mongoid::Document with an "embedded_in" is loaded.

module Products
class Preview
include Mongoid::Document
...
embedded_in :product
...
end
end

NoMethodError - undefined method `alias_method_chain' for Products::Preview:Class
Did you mean? alias_method:
mongoid-embedded-errors (2.1.1) lib/mongoid/embedded_errors.rb:9:in `included'
mongoid-embedded-errors (2.1.1) lib/mongoid/embedded_errors/embedded_in.rb:7:in `embedded_in'
app/models/products/preview.rb:8:in `<class:Preview>'
app/models/products/preview.rb:2:in `<module:Products>'
app/models/products/preview.rb:1:in `<top (required)>'
activesupport (5.1.3) lib/active_support/dependencies.rb:476:in `block in load_file'
activesupport (5.1.3) lib/active_support/dependencies.rb:661:in `new_constants_in'
activesupport (5.1.3) lib/active_support/dependencies.rb:475:in `load_file'
activesupport (5.1.3) lib/active_support/dependencies.rb:374:in `block in require_or_load'
activesupport (5.1.3) lib/active_support/dependencies.rb:36:in `block in load_interlock'
activesupport (5.1.3) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
activesupport (5.1.3) lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
activesupport (5.1.3) lib/active_support/dependencies/interlock.rb:11:in `loading'
activesupport (5.1.3) lib/active_support/dependencies.rb:36:in `load_interlock'
activesupport (5.1.3) lib/active_support/dependencies.rb:357:in `require_or_load'
activesupport (5.1.3) lib/active_support/dependencies.rb:510:in `load_missing_constant'
activesupport (5.1.3) lib/active_support/dependencies.rb:202:in `const_missing'
app/models/product.rb:55:in `<class:Product>'
app/models/product.rb:1:in `<top (required)>'

**Comment by VILATTI** [comment]
Any solutions?

**Comment by asgerb** [comment]
@VILATTI I put this in my Gemfile to fix this:

```
# Until newest version is released
gem 'mongoid-embedded-errors', git: 'git@github.com:glooko/mongoid-embedded-errors', branch: 'master'
```

I wonder why a new version hasn't been released?

**Comment by joe1chen** [comment]
+1 Can one of the maintainers release a new gem?

**Comment by knovoselic** [comment]
Closing as this is very old. If still relevant, please open a new issue.
